/**
 * Installing the native messaging host manifest.
 *
 * Chrome will not talk to a native host it has no manifest for, and the
 * manifest names both the executable and the single extension id allowed to
 * reach it. Writing it is therefore a deliberate, re-runnable step rather than
 * something that happens silently at launch.
 */

import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';
import {
  NATIVE_HOST_DIRECTORIES,
  NATIVE_HOST_NAME,
  nativeHostManifest,
  unpackedExtensionId,
} from './extension-id.js';

export interface InstallResult {
  extensionId: string;
  extensionDir: string;
  hostPath: string;
  /** Manifests actually written; a browser that is not installed is skipped. */
  written: string[];
  /** Browser directories that were absent. */
  skipped: string[];
}

export interface InstallOptions {
  /** The built, loadable extension directory — what you point Chrome at. */
  extensionDir: string;
  /** The relay script Chrome will execute. */
  hostPath: string;
  /** Where the generated wrapper goes; defaults to beside the relay. */
  wrapperPath?: string;
  /** Absolute interpreter to bake in. Defaults to the running one. */
  interpreter?: string;
  /** Passed to the wrapper's env, for running the relay under Electron. */
  interpreterEnv?: Record<string, string>;
  home?: string;
}

/**
 * A shell wrapper with an absolute interpreter path baked in.
 *
 * The relay's shebang is `#!/usr/bin/env node`, and Chrome does not have `node`
 * on its PATH. A browser launched from the Dock inherits almost nothing —
 * `/usr/bin:/bin:/usr/sbin:/sbin` — and a Homebrew or nvm Node is in none of
 * those. The host then fails to start, and the extension shows "UI Atlas is not
 * running" forever with no way to find out why.
 *
 * This is the same failure the supervisor already avoids by running child
 * processes under `process.execPath`; the relay needed the same treatment,
 * one layer out.
 */
export function wrapperScript(interpreter: string, hostPath: string, env: Record<string, string> = {}): string {
  const exported = Object.entries(env)
    .map(([key, value]) => `${key}=${shellQuote(value)}`)
    .join(' ');
  return (
    '#!/bin/sh\n' +
    '# Generated by `npm run launcher:install-extension`. Do not edit.\n' +
    '# Chrome executes this directly and has no useful PATH, so the\n' +
    '# interpreter is absolute rather than resolved at run time.\n' +
    `exec ${exported === '' ? '' : `env ${exported} `}${shellQuote(interpreter)} ${shellQuote(hostPath)} "$@"\n`
  );
}

/** Single quotes, with embedded single quotes closed and reopened. */
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Write `com.ui_atlas.launcher.json` into every Chromium-family browser
 * directory that exists. Only directories that are already there are written
 * to: creating one would be this tool inventing a browser profile.
 */
export async function installNativeHost(options: InstallOptions): Promise<InstallResult> {
  const home = options.home ?? homedir();
  const extensionId = unpackedExtensionId(options.extensionDir);

  // Chrome runs the wrapper, not the relay, so it never has to find `node`.
  const wrapperPath = options.wrapperPath ?? join(dirname(options.hostPath), 'native-host.sh');
  await writeFile(
    wrapperPath,
    wrapperScript(options.interpreter ?? process.execPath, options.hostPath, options.interpreterEnv ?? {}),
    'utf8',
  );
  await chmod(wrapperPath, 0o755);

  const manifest = nativeHostManifest(wrapperPath, extensionId);
  const body = `${JSON.stringify(manifest, null, 2)}\n`;

  const written: string[] = [];
  const skipped: string[] = [];

  for (const relative of NATIVE_HOST_DIRECTORIES) {
    const directory = join(home, relative);
    // The *parent* is the evidence the browser exists; the NativeMessagingHosts
    // directory itself often does not until something creates it.
    if (!existsSync(dirname(directory))) {
      skipped.push(directory);
      continue;
    }
    await mkdir(directory, { recursive: true });
    const path = join(directory, `${NATIVE_HOST_NAME}.json`);
    await writeFile(path, body, 'utf8');
    written.push(path);
  }

  return { extensionId, extensionDir: options.extensionDir, hostPath: wrapperPath, written, skipped };
}

/** What to tell the user once the manifest is in place. */
export function installSummary(result: InstallResult): string[] {
  const lines = [
    `extension id: ${result.extensionId}`,
    `load unpacked from: ${result.extensionDir}`,
  ];
  if (result.written.length === 0) {
    lines.push('no Chromium-family browser was found, so no host manifest was written');
    return lines;
  }
  for (const path of result.written) lines.push(`wrote ${path}`);
  lines.push(
    'The id above is derived from that directory path, so moving the checkout',
    'means running this again.',
  );
  return lines;
}
